config/routes.rb
Herpcs110s::Application.routes.draw do

  get "share/publish"

  resources :session
  resources :profiles
  resources :share
  
  resources :health_records, :workout_records, :injury_records
  resources :exercises, :workouts, :goals, :events, :trainers, :personal_records
  resource  :dashboard

  
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout

  match '/help', :to => 'home#index', :as => :help
  match '/about', :to => 'about#index', :as => :about_us
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/stats' => 'stats#index', :as => :stats
  
  match '/share' => 'share#create', :via => :post  
  
  root :to => "home#index"
end

app/models/workout.rb
# Stores data for built-in and custom workouts.
class Workout < ActiveRecord::Base

  # ----- ATTRIBUTES ACCESSIBLE -----
  attr_accessible :name, :description, :workout_category_attributes, :exercises_attributes

  # ----- NAMED SCOPES -----
  # order exercises by their categories in ascending order
  scope :ordered, :include => :workout_category, :order => 'workout_categories.category ASC'
  scope :name_ordered, :order => 'name ASC'
  scope :categorized, :include => :workout_category, :group => 'workout_categories.category'

  # ----- ASSOCIATIONS -----
  belongs_to  :workout_category
  has_many :exercise_workouts
  has_many :exercises, :through => :exercise_workouts
  accepts_nested_attributes_for :exercises
  accepts_nested_attributes_for :workout_category


  # ----- CLASS METHODS -----
  # Returns all official workouts
  def self.select_official_workouts
    Workout.where(:user_id => 1)
  end

  # Returns all custom workouts for user_id
  def self.select_custom_workouts(user_id)
    User.find_by_id(user_id).workouts
  end

  # ----- INSTANCE METHODS -----
  def associate_exercises_with(current_user_id)
    es = self.exercises.where(:user_id => nil)
    es.each do |e|
      User.find_by_id(current_user_id).exercises << e
      e.save
    end
  end

  def workout_category_attributes=(category)
      self.workout_category = WorkoutCategory.find_by_id(category[:category])
    unless self.workout_category
      self.workout_category = WorkoutCategory.find_or_initialize_by_category(category)
    end
  end
end

app/controllers/workouts_controller.rb
# Handles CRUD for workouts, custom and built-in.
# Built-in predefined workouts are referred to as "official".
class WorkoutsController < ApplicationController
  before_filter :set_up_workouts
  before_filter :set_up_categories

  # display list of all workout
  def index
    @title = 'Workouts'
  end

  # return an HTML form to add new workout
  def new
    @title = 'Add Workout'
    @workout = current_user.workouts.build 
    @workout.exercises.build
    current_user.exercises << @workout.exercises
    @workout.exercises.each do |e|
      e.exercise_category = ExerciseCategory.new
      # associate the new category with current user
      current_user.exercise_categories << e.exercise_category
    end
    @workout.workout_category = WorkoutCategory.new
  end

  # create a new workout
  def create
    # create new workout
    if params[:create_workout_category]
      category = WorkoutCategory.find_or_new_by_category(current_user.id, params[:create_category])
      params[:workout][:workout_category_attributes][:category] = category.category
      @workout = Workout.new params[:workout]
      @workout.workout_category = category
      set_up_categories
    elsif params[:add_exercise]
      exercises_attributes = params[:workout].delete(:exercises_attributes)
      @workout = Workout.new params[:workout]
      if exercises_attributes.present?
        @workout.exercises = exercises_attributes.map do |exercise_attributes|
          Exercise.find_or_new_by_attributes(current_user.id, exercise_attributes)
        end
      end
      @workout.exercises.build
      @workout.exercises.each do |e|
        unless e.exercise_category
          e.exercise_category = ExerciseCategory.new
        end
      end
    elsif params[:remove_exercise]
      @workout = Workout.new params[:workout]
      # they have destry attributes handled automatically by rails
    elsif params[:add_exercise_category]
      category = ExerciseCategory.find_or_new_by_category(current_user.id, params[:create_exercise_category])
      exercises_attributes = params[:workout].delete(:exercises_attributes)
      @workout = Workout.new params[:workout]
      if exercises_attributes.present?
        @workout.exercises = exercises_attributes.map do |exercise_attributes|
          Exercise.find_or_new_by_attributes(current_user.id, exercise_attributes)
        end
      end
      set_up_categories
    else
      exercises_attributes = params[:workout].delete(:exercises_attributes)
      @workout = Workout.new params[:workout]
      if exercises_attributes.present?
        @workout.exercises = exercises_attributes.map do |exercise_attributes|
          Exercise.find_or_new_by_attributes(current_user.id, exercise_attributes)
        end
      end
      if @workout.save
        # associate workout with user
        @workout.associate_exercises_with(current_user.id)
        current_user.workouts << @workout
        # display the workout
        redirect_to :action => 'show', :id => @workout.id
        return
      else
        flash.now[:error] = 'There was a problem saving your workout'
        flash.now[:errors] = @workout.errors
      end
    end
    render :action => 'new'
  end

  # display a specific workout
  def show
    @workout = Workout.select_official_workouts.find_by_id(params[:id])
     unless @workout
       @workout = current_user.workouts.find_by_id(params[:id])
     end
     unless @workout
      flash[:error] = "You do not have permission to view this workout"
      redirect_to :action => 'index'
      return
    end
    @title = "Workout - #{@workout.name}"
  end

  # return a form to edit a workout
  def edit
    @workout = current_user.workouts.find_by_id(params[:id])
    unless @workout
      flash[:error] = "You can't edit workouts that don't belong to you"
      redirect_to :action => 'index'
    end
    @title = "Edit Workout"
  end

  # update a specific workout
  def update
    @workout = Workout.find(params[:id])
    if params[:add_exercise]
        exercises_attributes = params[:workout].delete(:exercises_attributes)
        if exercises_attributes.present?
          @workout.exercises = exercises_attributes.map do |exercise_attributes|
            Exercise.find_or_new_by_attributes(current_user.id, exercise_attributes)
          end
        end
        @workout.exercises.build
        @workout.exercises.each do |e|
          unless e.exercise_category
            e.exercise_category = ExerciseCategory.new
          end
        end
    elsif params[:remove_exercise]
      # collect all marked for delete exercise ids
      removed_exercises = params[:workout][:exercises_attributes].collect { |i, att| att[:id] if (att[:id] && att[:_destroy].to_i == 1) }
      flash[:notice] = "Exercises removed."
      exercises_attributes = params[:workout].delete(:exercises_attributes)
      if exercises_attributes.present?
        exercises = exercises_attributes.map do |exercise_attributes|
          if exercise_attributes[1][:_destroy].to_i == 0
            Exercise.find_or_new_by_attributes(current_user.id, exercise_attributes)
          else
            nil
          end
        end
        @workout.exercises = exercises.compact
      end
      if @workout.exercises.blank?
        @workout.exercises.build
        @workout.exercises.each do |e|
          unless e.exercise_category
            e.exercise_category = ExerciseCategory.new
          end
        end
      end
    elsif params[:add_exercise_category]
      category = ExerciseCategory.find_or_new_by_category(current_user.id, params[:create_exercise_category])
      set_up_categories
    else
      # save goes like usual
      exercises_attributes = params[:workout].delete(:exercises_attributes)
      if @workout.update_attributes(params[:workout])
        if exercises_attributes.present?
          @workout.exercises = exercises_attributes.map do |exercise_attributes|
            Exercise.find_or_new_by_attributes(current_user.id, exercise_attributes)
          end
        end
        @workout.exercises.build
        @workout.exercises.each do |e|
          unless e.exercise_category
            e.exercise_category = ExerciseCategory.new
          end
        end
        @workout.associate_exercises_with(current_user.id)
        flash[:notice] = "Successfully updated workout."
        redirect_to @workout and return
      end
    end
    render :action => 'edit'
  end

  # delete a specific workout
  def destroy
    @workout = current_user.workouts.find_by_id(params[:id])
    unless @workout
      flash[:error] = 'You are not permitted to delete this workout'
      redirect_to :action => 'index'
    end
    @workout.destroy
    flash[:notice] = 'Successfully deleted workout'
    redirect_to :action => 'index'
  end

  private
    def set_up_workouts
      @officialWorkouts = Workout.select_official_workouts.ordered
      @customWorkouts = current_user.workouts.ordered
      @workouts = @officialWorkouts + @customWorkouts
    end

    def set_up_categories
      @officialCategories = WorkoutCategory.select_official_categories.ordered
      @customCategories = current_user.workout_categories.ordered
      @categories = @officialCategories + @customCategories
      @names = []
      @categories.each do |c|
        @names << c.category
      end
      @officialExerciseCategories = ExerciseCategory.select_official_categories.ordered
      @customExerciseCategories = current_user.exercise_categories.ordered
      @exerciseCategories = @officialExerciseCategories + @customExerciseCategories
      @exerciseNames = []
      @exerciseCategories.each do |c|
        @exerciseNames << c.category
      end
    end
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/workouts/edit.html.erb
<div class="row">
    <div class="span8">
      <h1>Edit Workout</h1>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span6">
        <%= form_for @workout, :html => { :class => 'form-vertical' }, :url => { :action => "update" } do |f| %>
        <fieldset class="control-group">
            <%= label_tag :name, 'Name' %>
            <%= f.text_field :name, :placeholder => "new workout name"%><br />
            <%= label_tag :description, 'Description' %>
            <%= f.text_area :description, :size => "20x5" %><br />
            <%= f.fields_for :workout_category do |wc| %>
              <%= label_tag :category, 'Category' %>
              <%= wc.select :category, @categories.collect{|c| [c.category, c.category]}%>
              <br /><%= text_field_tag :create_category %>
            <%= f.submit 'Create Workout Category', :name => 'create_workout_category' %>
            <% end %>
            <h2>Add Exercises</h2>

              <%= f.fields_for :exercises do |e| %>
              <h3>Exercise</h3>
              Remove?
              <%= e.check_box :_destroy %> 
              <%= e.fields_for "exercise_category" do |ec| %>
                <%= label_tag :category, 'Category' %>
                <%= ec.select :category, @exerciseCategories.collect{|c| [c.category, c.id]}%>
                <%= text_field_tag :create_exercise_category, nil, :placeholder => 'Create new exercise category' %>
                <%= f.submit 'Create Exercise Category', :name => 'add_exercise_category' %>
              <% end %>

              <%= e.label :repetitions %>
              <%= e.text_field :repetitions %>
              <%= e.label :weight %>
              <%= e.text_field :weight%><br />
              <%= e.label :distance %>
              <%= e.text_field :distance %>
              <%= e.label :units %>
              <%= e.text_field :units %>
              <%= e.label :rounds %>
              <%= e.text_field :rounds %>
              <%#= e.label :description %>
              <%#= e.text_field :description %>
              <% end -%>
            <br />
            <%= f.submit 'Add Exercise', :name => 'add_exercise' %>
            <%= f.submit 'Delete checked exercises', :name => 'remove_exercise' %>
            <br />
            <%= f.submit "Save", :class => 'btn btn-primary' %>
        </fieldset>
        <% end %>
    </div>
</div>

app/views/workouts/index.html.erb
<div class="row">
    <div class="span8">
        <h1>Workouts</h1>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span6">
        <h2>Standard Workouts</h2>
        <% if @officialWorkouts %>
          <% @officialWorkouts.group_by(&:workout_category).sort.each do |c,ws| %>
            <br /><h3><%= c.category %></h3>
              <% ws.each do |w| %>
                <%= link_to "#{w.name}", workout_path(w) %><br />
              <% end %>
          <% end %>
        <% end %>
        <br />
        <h2>Custom Workouts</h2> 
        <%= link_to "Add Workout", new_workout_path, :class => 'btn btn-primary' %><br />
        <% if @customWorkouts %>
          <% @customWorkouts.group_by(&:workout_category).sort.each do |c,ws| %>
            <br /><h3><%= c.category %></h3>
              <% ws.each do |w| %>
                <%= link_to "#{w.name}", workout_path(w) %><br />
              <% end %>
          <% end %>
        <% else %>
          <p>You have no custom workouts at this time</p>
        <% end %>
    </div>
</div>

app/views/workouts/new.html.erb
<div class="row">
    <div class="span8">
      <h1>Create Workout</h1>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span6">
        <%= form_for @workout, :html => { :class => 'form-vertical' }, :url => { :action => "create" } do |f| %>
        <fieldset class="control-group">
            <%= label_tag :name, 'Name' %>
            <%= f.text_field :name, :placeholder => "My new workout"%><br />
            <%= label_tag :description, 'Description' %>
            <%= f.text_area :description, :placeholder => "Super awesomeness", :size => "20x5" %><br />
            <%= f.fields_for :workout_category do |wc| %>
              <%= label_tag :category, 'Category' %>
              <%= wc.select :category, @categories.collect{|c| [c.category, c.category]}%>
              <br /><%= text_field_tag :create_category %>
            <%= f.submit 'Create Workout Category', :name => 'create_workout_category' %>
            <% end %>

            <h2>Add Exercises</h2>
              <%= f.fields_for :exercises do |e| %>
              <h3>Exercise </h3>
              Remove?
              <%= e.check_box :_destroy %> 
              <%= e.fields_for "exercise_category" do |ec| %>
                <%= label_tag :category, 'Category' %>
                <%= ec.select :category, @exerciseCategories.collect{|c| [c.category, c.id]}%>
                <br /><%= text_field_tag :create_exercise_category, nil, :placeholder => 'Create new exercise category' %>
                <%= f.submit 'Create Exercise Category', :name => 'add_exercise_category' %>
              <% end %>
              <p>Fill out as needed:</p>
              <%= e.label :repetitions %>
              <%= e.text_field :repetitions %>
              <%= e.label :weight %>
              <%= e.text_field :weight%>
              <%= e.label :distance %>
              <%= e.text_field :distance %>
              <%= e.label :units %>
              <%= e.text_field :units %>
              <%= e.label :rounds %>
              <%= e.text_field :rounds %>
              <%#= e.label :description %>
              <%#= e.text_field :description %>
              <% end -%>
            <br />
            <%= f.submit 'Add Exercise', :name => 'add_exercise' %>
            <%= f.submit 'Delete checked exercises', :name => 'remove_exercise' %>
            <br /><br />
            <%= f.submit "Save New Workout", :class => 'btn btn-primary' %>
        </fieldset>
        <% end %>
    </div>
</div>

app/views/workouts/show.html.erb
<div class="row">
    <div class="span8">
        <h2><%= link_to 'Back to Workouts', workouts_path %>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span6">
        <% if @workout.workout_category %>
        <h2><%= @workout.workout_category.category %>
      <% end %>
      <% if @workout.name %>
           - <%= @workout.name %></h2>
      <% end %>
      <% if @workout.description %>
          <%= @workout.description%><br />
      <% end %>
      <br />
      <h2>Components</h2> 
      <% @workout.exercises.each do |e| %>
        <% if e.exercise_category %>
          <strong><%= e.exercise_category.category %>:</strong><br />
        <% end %>
        <% if e.repetitions %>
            Repetitions: <%= e.repetitions %><br />
        <% end %>
        <% if e.weight %>
            Weight: <%= e.weight%> <%= e.units %><br />
        <% end %>
        <% if e.distance %>
             Distance: <%= e.distance %> <%= e.units %><br />
        <% end %>
        <% if e.rounds %>
            Rounds: <%= e.rounds %><br />
        <% end %>
        <% if e.description %>
            Description: <%= e.description %><br />
        <% end %>
        <br />
      <% end %>

      <% unless @workout.user_id == 1 %>
        <%= link_to 'Edit', edit_workout_path(@workout), :class => 'btn btn-primary'%>
        <%= link_to 'Delete', workout_path(@workout),
            :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-primary' %>
      <% end %>

    </div>
</div>

<div class="row">
    </br>
    <%= link_to "Do Workout", new_workout_record_path + "?workout=#{@workout.id}", :class => 'btn-large btn-primary' %>
</div>