config/routes.rb
Herpcs110s::Application.routes.draw do

  get "share/publish"

  resources :session
  resources :profiles
  resources :share
  
  resources :health_records, :workout_records, :injury_records
  resources :exercises, :workouts, :goals, :events, :trainers, :personal_records
  resource  :dashboard

  
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout

  match '/help', :to => 'home#index', :as => :help
  match '/about', :to => 'about#index', :as => :about_us
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/stats' => 'stats#index', :as => :stats
  
  match '/share' => 'share#create', :via => :post  
  
  root :to => "home#index"
end

app/controllers/home_controller.rb
require 'uri'

# Renders the home page.
class HomeController < ApplicationController
  skip_before_filter :require_login

  # Renders the home page or redirects to dashboard if user is logged in.
  def index
    if current_user
      if !request.referer || (request.env['HTTP_REFERER'] && !(URI(request.env['HTTP_REFERER']).path == dashboard_path))
        redirect_to :controller => 'dashboards', :action => 'show'
      end
    end
    @title = 'Home'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<style type="text/css">
.bfloatable {
  position: relative;
}
.float_from_bottom {
  position: absolute;
  margin-bottom: 5;
}
</style>
<script type="application/javascript">
$(document).ready(function() {
    $('.span4').css({
        'height': $('.span4').height()+75
    });
  });
</script>
<div class="row">
  <!-- <h1>Urban Crossfitters</h1> -->
  <div class = "hero-unit">
    <%= image_tag src=image_path('cs110logo3.png') %>
    <p>Welcome <%= 'back' if current_user %> to HERP's web application, Urban Crossfitters.</p>
    <p> <% if current_user %>
          <%= link_to 'Continue to Dashboard', dashboard_path, :class => 'btn btn-info btn-large' %>
        <% else %>
          <a href="<%= login_path %>" class="btn btn-info btn-large">Log in with Facebook &raquo;</a>
        <% end %></p>
  </div>
  <!-- Example row of columns -->
  <div class="row-fluid">
    <div class="span4 bfloatable">
      <h2><i class="icon-user"></i>Profile</h2>
      <p>View or edit your profile.</p>
      <%= content_tag :p,link_to('View details ', profiles_path+'/me', :class => 'btn btn-info float_from_bottom') %>
    </div>
    <div class="span4 bfloatable">
      <h2><i class="icon-fire"></i>Workout</h2>
      <p>Execute a workout or view your history.</p>
      <%= content_tag :p,link_to('View details ', workout_records_path, :class => 'btn btn-info float_from_bottom') %>
    </div>
    <div class="span4 bfloatable">
      <h2><i class="icon-heart"></i>Health</h2>
      <p>View or modify your health statistics.</p>
      <%= content_tag :p,link_to('View details ', health_records_path, :class => 'btn btn-info float_from_bottom') %>
    </div>  
  </div>
    <div class="row-fluid">
      <div class="span4 bfloatable">
        <h2><i class="icon-calendar"></i>Calendar</h2>
        <p>Create, view, or edit your calendar entries.</p>
        <p class="float_from_bottom"><%= link_to('View details ', calendar_path, :class => 'btn btn-info') %></p>
      </div>
      <div class="span4 bfloatable">
        <h2><i class="icon-flag"></i>Goals</h2>
        <p>Manage your goals.</p>
        <p class="float_from_bottom"><%= link_to 'View details', goals_path, :class => 'btn btn-info' %></p>
     </div>
     <div class="span4 bfloatable">
      <h2><i class="icon-tasks"></i>Stats</i></h2>
      <p>View your workout statistics.</p>
      <p class="float_from_bottom"><%= link_to 'View details', stats_path, :class => 'btn btn-info' %></p>
    </div>
  </div>
</div>