config/routes.rb
Herpcs110s::Application.routes.draw do

  get "share/publish"

  resources :session
  resources :profiles
  resources :share
  
  resources :health_records, :workout_records, :injury_records
  resources :exercises, :workouts, :goals, :events, :trainers, :personal_records
  resource  :dashboard

  
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout

  match '/help', :to => 'home#index', :as => :help
  match '/about', :to => 'about#index', :as => :about_us
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/stats' => 'stats#index', :as => :stats
  
  match '/share' => 'share#create', :via => :post  
  
  root :to => "home#index"
end

app/models/event.rb
# Polymorphic model to store events for
# Goal, WorkoutRecord, and InjuryRecord
# and render in the calendar.
class Event < ActiveRecord::Base

  # ----- ATTRIBUTES ACCESSIBLE -----
  attr_accessible :name, :start_at, :end_at, :user, :event_color

  # ----- NAMED SCOPES -----
  scope :ordered, :order => 'end_at DESC'

  # ----- ASSOCIATIONS ----- 
  belongs_to      :event_color
  belongs_to      :user
  belongs_to      :schedulable, :polymorphic => true
  has_event_calendar

  # ----- INSTANCE METHODS -----
  # Returns the event's end_at date, or today's date
  # if end_at is nil.
  def end_at
    if self[:end_at]
      self[:end_at].to_date
    else
      Date.today
    end
  end
end

app/controllers/events_controller.rb
# EventsController handles index and show for
# Events and acts somewhat as glue to allow viewing
# of corresponding records for event strips in the calendar.
class EventsController < ApplicationController
  
  # Shows all of the current user's events
  def index
    @title = 'Events'
    @events = current_user.events.ordered
  end

  # View an individual event.
  def show
    @event = current_user.events.find_by_id(params[:id])
    @title = "Event - #{@event.name}"
    unless @event
      flash[:error] = "You aren't permitted to see this event"
      redirect_to :action => 'index'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="row">
    <div class="span8">
        <h1>Your Events</h1>
    </div>
</div>
<div class="row">
    <div class="span8">
      <% if @events.size > 0 %>
        <% @events.group_by(&:end_at).sort.reverse.each do |date, events| %>
          <h2><%= date %></h2>
          <% events.each do |event| %>
            <%= link_to "#{event.name}", event_path(event) %><br />
          <% end %>
        <% end %>
      <% else %>
        <p>You currently do not have any events.</p>
      <% end %>
    </div>
</div>

app/views/events/show.html.erb
<div class="row">
    <div class="span8">
        <h1>View Event</h1>
        <h2><%= link_to 'Back to Calendar', calendar_path %>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span6">
      <% sch = @event.schedulable %>
      <% if sch.is_a?(InjuryRecord) %>
        <h2><%= link_to sch.name, edit_injury_record_path(sch) %></h2>
	<p><%= sch.description %></p>
	<p><strong>Severity: </strong>
	    <span class="label">
	    <%= sch.severity %>
            </span>
	</p>
	<p><strong>Injury Date: </strong><%= sch.start_date %></p
	<% if sch.end_date %>>
	<p><strong>Recovery Date: </strong><%= sch.end_date %></p>
	<% else %>
	<p><strong>Recovery Date: </strong><%= 'Ongoing' %></p>
	<% end %>
      <% elsif sch.is_a?(WorkoutRecord) %>
        <% if sch.date_performed %>
          <%= sch.date_performed %></br>
        <% end %>
        <% if sch.note %>
            Note:<%= sch.note %><br />
        <% end %>
        <% if sch.points %>
            Points:<%= sch.points%><br />
        <% end %>
        <% if sch.time %>
             Time:<%= sch.time[:string] %><br />
        <% end %>
        <% if sch.rounds %>
            Rounds:<%= sch.rounds %><br />
        <%= link_to 'Edit Record', edit_workout_record_path(sch), :class => "btn btn-primary" %>
        <%= link_to 'Delete Record', workout_record_path(sch),
              :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-primary" %><br />

        <% end %>
      <% elsif sch.is_a?(Goal) %>
        <h2><%= link_to sch.name, edit_goal_path(sch.id) %></h2>
        <p><%= sch.description %></p>
        <p><strong>Status: </strong> 
            <span class="label<%= ' label-success' if sch.status == 'Complete' %>">
            <%= sch.status %>
            </span>
        </p>
        <p><strong>Deadline: </strong><%= sch.deadline %></p>
      <% end %>
    </div>
</div>