config/routes.rb
Herpcs110s::Application.routes.draw do

  get "share/publish"

  resources :session
  resources :profiles
  resources :share
  
  resources :health_records, :workout_records, :injury_records
  resources :exercises, :workouts, :goals, :events, :trainers, :personal_records
  resource  :dashboard

  
  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy', :as => :logout

  match '/help', :to => 'home#index', :as => :help
  match '/about', :to => 'about#index', :as => :about_us
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/stats' => 'stats#index', :as => :stats
  
  match '/share' => 'share#create', :via => :post  
  
  root :to => "home#index"
end

app/models/health_record.rb
# Records health-related metrics: blood pressure, weight, heart rate,
# and calories consumed over time.
class HealthRecord < ActiveRecord::Base

  # ----- ATTRIBUTES ACCESSIBLE -----
  attr_accessible :date_recorded, :systolic_bp, :diastolic_bp, :weight,
                  :resting_heart_rate, :calories_consumed

  # ----- NAMED SCOPE -----
  scope :ordered, :order => 'date_recorded DESC'
  scope :last_month, lambda { where( :date_recorded => (Date.today - 30.days)..Date.today ).ordered }
  
  # ----- ASSOCIATIONS -----
  belongs_to :user

  # ----- VALIDATION CALLS -----
  validate :at_least_one_health_metric
  validate :systolic_and_diastolic_present_together

  if validate :systolic_and_diastolic_present_together => true
    validates :systolic_bp,
              :numericality => { :only_integer => true, :allow_blank => true,
                                 :greater_than => 0 ,
                                  :message => 'Systolic bp must be an integer greater than 0'}
    validates :diastolic_bp,
              :numericality => { :only_integer => true, :allow_blank => true,
                                 :greater_than => 0 ,
                                 :message => 'Diastolic bp must be an integer greater than 0'}
  end

  validates :weight,
            :numericality => { :only_integer => true, :allow_blank => true,
                               :greater_than => 0 ,
                               :message => 'Weight must be an integer greater than 0'}
  validates :resting_heart_rate,
            :numericality => { :only_integer => true, :allow_blank => true,
                               :greater_than => 0 ,
                               :message => 'Resting heart rate must be an integer greater than 0'}

  validates :calories_consumed,
            :numericality => { :only_integer => true, :allow_blank => true,
                               :greater_than => 0 ,
                               :message => 'Calories consumed must be an integer greater than 0'}

  validates_date :date_recorded, :on_or_before => Date.current


  # ----- CUSTOM VALIDATION METHODS -----
  # Validation to ensure that at least one metric was provided
  def at_least_one_health_metric
    unless (self.systolic_bp || self.diastolic_bp || self.weight ||
            self.resting_heart_rate || self.calories_consumed)
      self.errors[:base] << 'At least one metric must be entered'
    end
  end

  # Ensures that both systolic and diastolic readings were provided if defining
  # blood pressure.
  def systolic_and_diastolic_present_together
    unless (self.systolic_bp && self.diastolic_bp ||
            !self.systolic_bp && !self.diastolic_bp)
      self.errors[:base] << 'Systolic and Diastolic blood pressure must be entered together'
    end
  end

  # Returns a tuple containing the series for systolic and diastolic
  # blood pressure over the last month for charting.
  def self.get_bp_series_for_chart(user_id)
    records = User.find_by_id(user_id).health_records.last_month
    sys_bp = HealthRecord.series_from_collection records, :systolic_bp
    dia_bp = HealthRecord.series_from_collection records, :diastolic_bp
    return sys_bp, dia_bp
  end

  def self.get_heart_rate_series_for_chart(user_id)
    records = User.find_by_id(user_id).health_records.last_month
    heart_rate = HealthRecord.series_from_collection records, :resting_heart_rate
  end

  def self.get_weight_series_for_chart(user_id)
    records = User.find_by_id(user_id).health_records.last_month
    weight = HealthRecord.series_from_collection records, :weight
  end

  def self.get_bmi_series_for_chart(user_id)
    records = HealthRecord.get_weight_series_for_chart user_id
    user = User.find_by_id(user_id)
    if not user.profile
      return []
    end
    height = user.profile[:height]

    records.map! { |r| [r[0], HealthRecord.calculate_bmi(r[1], height)] }
    return records
  end

  def self.get_calories_series_for_chart(user_id)
    records = User.find_by_id(user_id).health_records.last_month
    calories = HealthRecord.series_from_collection records, :calories_consumed
  end

  def self.calculate_bmi(weight_pounds, height_inches)
    ( weight_pounds.to_f / (height_inches.to_f**2) ) * 703
  end

  def self.series_from_collection(collection, column)
    series = []
    collection.each do |r|
      recorded_date = r.date_recorded.to_time.tv_sec * 1000
      series << [recorded_date, r[column]] if r[column]
    end
    return series
  end
end

app/controllers/health_records_controller.rb
# Handles CRUD for HealthRecords.
class HealthRecordsController < ApplicationController
  # display list of all health records for a user
  def index
    @records = current_user.health_records.ordered
    @title = 'Health Records'
  end

  # return an HTML form to add a health record
  def new
    @title = 'New Health Record'
    @record = HealthRecord.new
  end

  # create a new health record
  def create
    @record = HealthRecord.new(params[:health_record])
    if @record.save
      current_user.health_records << @record
      redirect_to :action => 'show', :id => @record.id
    else
      flash[:error] = 'There was a problem saving your health record'
      flash[:errors] = @record.errors
      redirect_to :action => 'new'
    end
  end

  # display a specific health record
  def show
    @title = 'View Health Record'
    # only select from records that are associated with current user
    @record = current_user.health_records.find_by_id(params[:id])
    unless @record
      flash[:error] = "The selected health record doesn't belong to you"
      redirect_to :action => 'index'
    end
  end

  # return a form to edit a health record
  def edit
    @title = 'Edit Health Record'
    # only select from records that are associated with current user
    @record = current_user.health_records.find_by_id(params[:id])
    unless @record
      flash[:error] = "The selected health record doesn't belong to you"
      redirect_to :action => 'index'
    end
  end

  # update a specific health record
  def update
    # only select from records that are associated with current user
    @record = current_user.health_records.find_by_id(params[:id])
    unless @record
      flash[:error] = "The selected health record doesn't belong to you"
      redirect_to :action => 'index'
    end
    if @record.update_attributes(params[:health_record])
      flash[:notice] = 'Edit was successful'
      redirect_to :action => 'show', :id => @record.id
    else
      flash[:error] = "Your health record didn't update properly"
      flash[:errors] = @record.errors
      redirect_to :action => 'edit', :id => @record.id
    end
  end

  # delete a specific health record
  def destroy
    # only select from records that are associated with current user
    @record = current_user.health_records.find_by_id(params[:id])
    @record.destroy
    redirect_to :action => 'index'
  end
end

app/helpers/health_records_helper.rb
module HealthRecordsHelper
end

app/views/health_records/edit.html.erb
<div class="row">
    <div class="span8">
      <h1>Edit Health Record</h1>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span4">
    
        <%= form_for @record, :html => { :class => 'form-vertical' }, :url => { :action => "update" } do |f| %>
        <fieldset class="control-group">
            <%= label_tag :date_recorded, 'Date Recorded' %>
            <%= f.date_select :date_recorded, :end_year => Time.now.year %>
            <%= label_tag :systolic_bp, 'Systolic Blood Pressure' %>
            <%= f.text_field :systolic_bp %>
            <%= label_tag :diastolic_bp, 'Diastolic Blood Pressure' %>
            <%= f.text_field :diastolic_bp %>
            <%= label_tag :weight, 'Weight' %>
            <%= f.text_field :weight %>
            <%= label_tag :resting_heart_rate, 'Resting Heart Rate' %>
            <%= f.text_field :resting_heart_rate %>
            <%= label_tag :calories_consumed, 'Consumed Calories' %>
            <%= f.text_field :calories_consumed %>
            <%= f.submit "Save changes", :class => 'btn btn-primary' %>
        </fieldset>
        <% end %>
    </div>
</div>

app/views/health_records/index.html.erb
<div class="row">
  <div class="span6">
    <h1>Your Health Records</h1>
  </div>
</div>
    <div class="row">
      <div class="span6">
        <%= link_to "Add Health Record", new_health_record_path, :class => "btn btn-primary" %></br>
      </div>
    </div>
<% if @records %>
    <% @records.each do |record| %>
        <div class="row">
	    <div class ="span6">
               <%= link_to "#{record.date_recorded}", health_record_path(record) %>
            </div>
	</div>
    <% end %>
<% else %>
    <div class="row">
        <div class="span6">
	    <h3>You currently have no health records.</h3>
	</div>
    </div>
<% end %>

app/views/health_records/new.html.erb
<div class="row">
    <div class="span8">
      <h1>Create Health Record</h1>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span4">
        <%= form_for @record, :html => { :class => 'form-vertical' }, :url => { :action => "create" } do |f| %>
        <fieldset class="control-group">
            <%= label_tag :date_recorded, 'Date Recorded' %>
            <%= f.date_select :date_recorded, :end_year => Time.now.year, :order => [:month, :day, :year] %>
            <%= label_tag :systolic_bp, 'Systolic Blood Pressure' %>
            <%= f.text_field :systolic_bp %>
            <%= label_tag :diastolic_bp, 'Diastolic Blood Pressure' %>
            <%= f.text_field :diastolic_bp %>
            <%= label_tag :weight, 'Weight' %>
            <%= f.text_field :weight %>
            <%= label_tag :resting_heart_rate, 'Resting Heart Rate' %>
            <%= f.text_field :resting_heart_rate %>
            <%= label_tag :calories_consumed, 'Consumed Calories' %>
            <%= f.text_field :calories_consumed %>
            <%= f.submit "Create Record", :class => 'btn btn-primary' %>
        </fieldset>
        <% end %>
    </div>
</div>

app/views/health_records/show.html.erb
<div class="row">
    <div class="span8">
        <h1>View Health Record</h1>
        <h2><%= link_to 'Back to Records', health_records_path %>
    </div>
</div>&nbsp;
<div class="row">
    <div class="span6">
      <h3><%= @record.date_recorded %></h3></br>
      <% if @record.systolic_bp && @record.diastolic_bp %>
          <b>Diastolic Blood Pressure: </b><%= @record.systolic_bp %><br />
          <b>Systolic Blood Pressure: </b><%= @record.diastolic_bp %><br />
      <% end %>
      <% if @record.weight %>
          <b>Weight: </b><%= @record.weight %><br />
      <% end %>
      <% if @record.resting_heart_rate %>
          <b>Resting Heart Rate: </b><%= @record.resting_heart_rate %><br />
      <% end %>
      <% if @record.calories_consumed %>
          <b>Calories Consumed: </b><%= @record.calories_consumed %><br />
      <% end %>
      <%= link_to 'Edit Record', edit_health_record_path(@record), :class => "btn btn-primary" %>
      <%= link_to 'Delete Record', health_record_path(@record),
            :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-primary" %><br />
    </div>
</div>